### ISSUE TITLE
Adding telegram web apps support

### ISSUE THREAD

**Issue by axyonovleonid** [kshashov/spring-boot-starter-telegram#28]
I'd like to implement by myself support for telegram web app
https://core.telegram.org/api/bots/webapps#simple-web-apps
What is the best way to do it in terms of api and reusability? Asking for a little guidance

**Comment by kshashov** [comment]
Hi Leonid, 
What exactly do you mean by "support for a telegram web app"?

The bot here is used here only to open the app and get the result from it. All this can already be done using this library since it is based on the https://github.com/pengrad/java-telegram-bot-api/. These are fairly simple steps and I don't think they need an additional simplified API. 

Please correct me if I'm wrong, I have never used web apps myself)

**Comment by axyonovleonid** [comment]
By web app I mean something like this (https://t.me/asmico_attach_bot), this (https://www.youtube.com/watch?v=MzO-0IYkZMU) and this (https://github.com/revenkroz/telegram-web-app-bot-example)
I think, for my purposes I'll implement BotHandlerMethodReturnValueHandler and just add needed fields to return messages. Just curious, if I can later commit it to improve current lib. I think, it's best framework for Java TG, so it can be usefull

**Comment by axyonovleonid** [comment]
Idk why  "new InlineKeyboardButton("google it").url("www.google.com")" smth like this isn't working, but will try to learn API at first, maybe I'm rushing

**Comment by kshashov** [comment]
Works fine for me:
```java
    @MessageRequest("/app")
    public SendMessage app(Chat chat) {
        InlineKeyboardButton showAppButton = new InlineKeyboardButton("Show Web App")
                .webApp(new WebAppInfo("https://www.google.com/"));

        SendMessage response = new SendMessage(chat.id(), "app");
        response.replyMarkup(new InlineKeyboardMarkup(showAppButton));

        return  response;
    }
```

**Comment by axyonovleonid** [comment]
Oh, now I see, I should have added lib you mentioned before. Thank you a lot!
